#pragma once

#include <array>

#define ASTRO_EXPAND(X) X

#define ASTRO_GET_NTH_ARG(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, NAME, ...) NAME

#define ASTRO_FE0(MAC, ...)
#define ASTRO_FE1(MAC,  A, B) MAC(A, B)
#define ASTRO_FE2(MAC,  A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE1(MAC,  A, __VA_ARGS__))
#define ASTRO_FE3(MAC,  A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE2(MAC,  A, __VA_ARGS__))
#define ASTRO_FE4(MAC,  A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE3(MAC,  A, __VA_ARGS__))
#define ASTRO_FE5(MAC,  A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE4(MAC,  A, __VA_ARGS__))
#define ASTRO_FE6(MAC,  A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE5(MAC,  A, __VA_ARGS__))
#define ASTRO_FE7(MAC,  A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE6(MAC,  A, __VA_ARGS__))
#define ASTRO_FE8(MAC,  A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE7(MAC,  A, __VA_ARGS__))
#define ASTRO_FE9(MAC,  A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE8(MAC,  A, __VA_ARGS__))
#define ASTRO_FE10(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE9(MAC,  A, __VA_ARGS__))
#define ASTRO_FE11(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE10(MAC, A, __VA_ARGS__))
#define ASTRO_FE12(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE11(MAC, A, __VA_ARGS__))
#define ASTRO_FE13(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE12(MAC, A, __VA_ARGS__))
#define ASTRO_FE14(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE13(MAC, A, __VA_ARGS__))
#define ASTRO_FE15(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE14(MAC, A, __VA_ARGS__))
#define ASTRO_FE16(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE15(MAC, A, __VA_ARGS__))
#define ASTRO_FE17(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE16(MAC, A, __VA_ARGS__))
#define ASTRO_FE18(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE17(MAC, A, __VA_ARGS__))
#define ASTRO_FE19(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE18(MAC, A, __VA_ARGS__))
#define ASTRO_FE20(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE19(MAC, A, __VA_ARGS__))
#define ASTRO_FE21(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE20(MAC, A, __VA_ARGS__))
#define ASTRO_FE22(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE21(MAC, A, __VA_ARGS__))
#define ASTRO_FE23(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE22(MAC, A, __VA_ARGS__))
#define ASTRO_FE24(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE23(MAC, A, __VA_ARGS__))
#define ASTRO_FE25(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE24(MAC, A, __VA_ARGS__))
#define ASTRO_FE26(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE25(MAC, A, __VA_ARGS__))
#define ASTRO_FE27(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE26(MAC, A, __VA_ARGS__))
#define ASTRO_FE28(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE27(MAC, A, __VA_ARGS__))
#define ASTRO_FE29(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE28(MAC, A, __VA_ARGS__))
#define ASTRO_FE30(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE29(MAC, A, __VA_ARGS__))
#define ASTRO_FE31(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE30(MAC, A, __VA_ARGS__))
#define ASTRO_FE32(MAC, A, B, ...) MAC(A, B) ASTRO_EXPAND(ASTRO_FE31(MAC, A, __VA_ARGS__))
#define ASTRO_FE_COMMA2(MAC,  A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE1(MAC,  A, __VA_ARGS__))
#define ASTRO_FE_COMMA3(MAC,  A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA2(MAC,  A, __VA_ARGS__))
#define ASTRO_FE_COMMA4(MAC,  A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA3(MAC,  A, __VA_ARGS__))
#define ASTRO_FE_COMMA5(MAC,  A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA4(MAC,  A, __VA_ARGS__))
#define ASTRO_FE_COMMA6(MAC,  A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA5(MAC,  A, __VA_ARGS__))
#define ASTRO_FE_COMMA7(MAC,  A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA6(MAC,  A, __VA_ARGS__))
#define ASTRO_FE_COMMA8(MAC,  A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA7(MAC,  A, __VA_ARGS__))
#define ASTRO_FE_COMMA9(MAC,  A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA8(MAC,  A, __VA_ARGS__))
#define ASTRO_FE_COMMA10(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA9(MAC,  A, __VA_ARGS__))
#define ASTRO_FE_COMMA11(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA10(MAC, A, __VA_ARGS__))
#define ASTRO_FE_COMMA12(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA11(MAC, A, __VA_ARGS__))
#define ASTRO_FE_COMMA13(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA12(MAC, A, __VA_ARGS__))
#define ASTRO_FE_COMMA14(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA13(MAC, A, __VA_ARGS__))
#define ASTRO_FE_COMMA15(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA14(MAC, A, __VA_ARGS__))
#define ASTRO_FE_COMMA16(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA15(MAC, A, __VA_ARGS__))
#define ASTRO_FE_COMMA17(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA16(MAC, A, __VA_ARGS__))
#define ASTRO_FE_COMMA18(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA17(MAC, A, __VA_ARGS__))
#define ASTRO_FE_COMMA19(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA18(MAC, A, __VA_ARGS__))
#define ASTRO_FE_COMMA20(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA19(MAC, A, __VA_ARGS__))
#define ASTRO_FE_COMMA21(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA20(MAC, A, __VA_ARGS__))
#define ASTRO_FE_COMMA22(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA21(MAC, A, __VA_ARGS__))
#define ASTRO_FE_COMMA23(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA22(MAC, A, __VA_ARGS__))
#define ASTRO_FE_COMMA24(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA23(MAC, A, __VA_ARGS__))
#define ASTRO_FE_COMMA25(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA24(MAC, A, __VA_ARGS__))
#define ASTRO_FE_COMMA26(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA25(MAC, A, __VA_ARGS__))
#define ASTRO_FE_COMMA27(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA26(MAC, A, __VA_ARGS__))
#define ASTRO_FE_COMMA28(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA27(MAC, A, __VA_ARGS__))
#define ASTRO_FE_COMMA29(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA28(MAC, A, __VA_ARGS__))
#define ASTRO_FE_COMMA30(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA29(MAC, A, __VA_ARGS__))
#define ASTRO_FE_COMMA31(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA30(MAC, A, __VA_ARGS__))
#define ASTRO_FE_COMMA32(MAC, A, B, ...) MAC(A, B), ASTRO_EXPAND(ASTRO_FE_COMMA31(MAC, A, __VA_ARGS__))

#define ASTRO_FOREACH_NO_COMMA(MAC, D, ...)  \
   ASTRO_GET_NTH_ARG("ignored", __VA_ARGS__, \
      ASTRO_FE32,ASTRO_FE31,ASTRO_FE30,ASTRO_FE29,ASTRO_FE28,ASTRO_FE27,ASTRO_FE26,ASTRO_FE25,ASTRO_FE24,ASTRO_FE23,ASTRO_FE22,ASTRO_FE21,ASTRO_FE20,ASTRO_FE19,ASTRO_FE18,ASTRO_FE17,ASTRO_FE16,ASTRO_FE15,ASTRO_FE14,ASTRO_FE13,ASTRO_FE12,ASTRO_FE11,ASTRO_FE10,ASTRO_FE9,ASTRO_FE8,ASTRO_FE7,ASTRO_FE6,ASTRO_FE5,ASTRO_FE4,ASTRO_FE3,ASTRO_FE2,ASTRO_FE1,ASTRO_FE0)(MAC, D, __VA_ARGS__)

#define ASTRO_FOREACH(MAC, D, ...)           \
   ASTRO_GET_NTH_ARG("ignored", __VA_ARGS__, \
      ASTRO_FE_COMMA32,ASTRO_FE_COMMA31,ASTRO_FE_COMMA30,ASTRO_FE_COMMA29,ASTRO_FE_COMMA28,ASTRO_FE_COMMA27,ASTRO_FE_COMMA26,ASTRO_FE_COMMA25,ASTRO_FE_COMMA24,ASTRO_FE_COMMA23,ASTRO_FE_COMMA22,ASTRO_FE_COMMA21,ASTRO_FE_COMMA20,ASTRO_FE_COMMA19,ASTRO_FE_COMMA18,ASTRO_FE_COMMA17,ASTRO_FE_COMMA16,ASTRO_FE_COMMA15,ASTRO_FE_COMMA14,ASTRO_FE_COMMA13,ASTRO_FE_COMMA12,ASTRO_FE_COMMA11,ASTRO_FE_COMMA10,ASTRO_FE_COMMA9,ASTRO_FE_COMMA8,ASTRO_FE_COMMA7,ASTRO_FE_COMMA6,ASTRO_FE_COMMA5,ASTRO_FE_COMMA4,ASTRO_FE_COMMA3,ASTRO_FE_COMMA2,ASTRO_FE1,ASTRO_FE0)(MAC, D, __VA_ARGS__)

#define ASTRO_EXPAND_STR(ignore, X) #X

#define ASTRO_VA_ARGS_SIZE(...) \
   (std::array{ ASTRO_FOREACH( ASTRO_EXPAND_STR, "ignore", __VA_ARGS__)}.size())
